version: "3.8"
services:
  xray:
    image: amazon/aws-xray-daemon
    ports:
    - "2000:2000/tcp"
    - "2000:2000/udp"
    env_file:
      - aws-credentials.env
  frontend:
    image: booking/frontend_service
    ports:
      - "8080:8080"
    links:
      - manage
      - search
      - xray
    environment:
    - AWS_XRAY_DAEMON_ADDRESS=xray:2000
  manage:
    image: booking/manage_service
    ports:
      - "8081:8081"
    links:
      - persistence
      - xray
    environment:
      - AWS_XRAY_DAEMON_ADDRESS=xray:2000
  search:
    image: booking/search_service
    ports:
      - "8082:8082"
    links:
      - persistence
      - xray
    environment:
      - AWS_XRAY_DAEMON_ADDRESS=xray:2000
  persistence:
    image: booking/persistence_service
    ports:
      - "8083:8083"
    links:
      - mysql
      - xray
    environment:
      - AWS_XRAY_DAEMON_ADDRESS=xray:2000
    env_file:
      - aws-credentials.env
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: booking
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword
volumes:
  db_data: {}